### ISSUE TITLE
Table is parsed as paragraph 

### ISSUE THREAD

**Issue by setdvd** [dillonkearns/elm-markdown#49] opened 2020-06-27 21:36 UTC
Looks like table is not parsed 

How to reproduce 

go to ellie https://ellie-app.com/8kQjvHM9hMfa1

paste md from github example for table:

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

it is rendered as paragraph / text

**Comment by dillonkearns** [comment] 2020-06-27 21:38
Hello @setdvd! Yes, we decided to ship the types to avoid a breaking change once we shipped the finished table parser. It was in progress so I didn't want to turn on the parsing before it handled all cases properly. Sorry for the confusing.

The issue is being tracked here already, so I'll close this one and we can keep track of progress here: https://github.com/dillonkearns/elm-markdown/issues/33

**Closed by dillonkearns** 2020-06-27 21:38 UTC
